default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: gravy-boat-dev

test:
  <<: *default
  database: gravy-boat-test

production:
  <<: *default
  database: gravy-boat-prod
